// <auto-generated />
using FizzBuzz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FizzBuzz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241220211213_AddFizzBuzzRuleWithPairs")]
    partial class AddFizzBuzzRuleWithPairs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DivisorWordPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Divisor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FizzBuzzRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FizzBuzzRuleId");

                    b.ToTable("DivisorWordPairs");
                });

            modelBuilder.Entity("FizzBuzzRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FizzBuzzRules");
                });

            modelBuilder.Entity("DivisorWordPair", b =>
                {
                    b.HasOne("FizzBuzzRule", "FizzBuzzRule")
                        .WithMany("DivisorWordPairs")
                        .HasForeignKey("FizzBuzzRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FizzBuzzRule");
                });

            modelBuilder.Entity("FizzBuzzRule", b =>
                {
                    b.Navigation("DivisorWordPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
