services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: FB_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d FB_database"]
      interval: 10s
      timeout: 5s
      retries: 5

  fizzbuzz-app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=FB_database;Username=admin;Password=admin
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:5000"
    restart: on-failure

volumes:
  postgres_data:
